dist: xenial
notifications:
  email: false
language: python
python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - pypy3.5
install:
  - pip install -U tox-travis
  - pip install -e .[dev]
  - python setup.py develop
script: tox
before_deploy:
  - python setup.py check -r -s
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password: $PYP
  on:
    tags: true
    branch: master
    python: 3.6
